name: Build Conda package

on:
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    # the -l flag is needed for the Conda environment to be activated properly
    shell: bash -l {0}

jobs:
  conda-build:
    name: Build Conda package (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build-psuade
          python-version: '3.7'
          channels: conda-forge
      - name: Run conda-build
        working-directory: .conda-build
        run: |
          conda install --quiet --yes conda-build
          conda list
          conda-build .
